### ISSUE TITLE
Rocks replacing log

### ISSUE THREAD

**Issue by KostromDan** [mc-jt9/ProjectVibrantJourneys#203]
![image](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/assets/90044015/745b516e-33fa-44b3-a64a-5f95be7a8eb4)
This looks ugly.

**Comment by KostromDan** [comment]
![image](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/assets/90044015/d304dff9-45fe-4d1f-9ea9-3ab8bee08e4d)

**Comment by OrderedChaos-Dev** [comment]
At one point I fixed this, no idea what version though. But closing as stale

**Comment by KostromDan** [comment]
@OrderedChaos-Dev 
On 1.19.2, it is still not fixed.
I assume it's because 1.19.2 has been abandoned.
Can you specify which commit fixed it, so I can backport the patch via datapack, mixins, or a PR?
This is an important issue for my modpack.

**Comment by KostromDan** [comment]
Done:
```java
@Mixin(RocksGroundcoverFeature.class)
public class RocksGroundcoverFeatureMixin {
    @Inject(
            at = @At("HEAD"),
            method = "place",
            cancellable = true
    )
    private void beforePlace(FeaturePlaceContext<RandomPatchConfiguration> context, CallbackInfoReturnable<Boolean> cir) {
        BlockPos origin = context.origin();
        WorldGenLevel level = context.level();
        BlockState originState = level.getBlockState(origin);
        if (!originState.getMaterial().isReplaceable() && !level.isEmptyBlock(origin)) {
            cir.setReturnValue(false);
            cir.cancel();
        }
    }
}
```
